# Site
repository: https://github.com/yutingcxiang/resume
# favicon: images/favicon.ico

# Personal info
name: Christine Xiang
title: Automation Engineer
email: yutingcxiang@gmail.com
website: https://yutingcxiang.github.io/resume/

# Social links
# twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Christine and I'm an automation engineer with expertise in data analytics, databases, and web development.

  I am most skilled in: <mark>JavaScript</mark> and <mark>analyzing data</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in web development and data analysis, some of my other interests and hobbies are:
   - Cooking
   - Gaming
   - Reading magazines
   - Trading stocks


# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
