# Site
repository: yutingcxiang/resume
# favicon: images/favicon.ico

# Personal info
name: Christine Xiang
title: Automation Engineer
email: yutingcxiang@gmail.com
# website: https://yutingcxiang.github.io/resume/

# Social links
# twitter_username: facespics
github_username:  yutingcxiang
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: yutingcxiang
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Christine and I'm an automation engineer with expertise in data analytics, databases, and web development.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: My Skillset
more_content: | # this will include new lines to allow paragraphs

  <mark>Languages​</mark> - JavaScript, Ruby, Python

  <mark>Databases</mark> - SQLite, PostgreSQL, MongoDB, SQL Server

  <mark>Frameworks</mark> - ​Rails, Sinatra, jQuery, React, Redux, Express, Node, Flask

  <mark>Web Development</mark> - ​​HTML5/CSS3, Bootstrap, Sass, Git, Heroku, AWS, Jira, Agile, Docker 

  <mark>Analytics</mark> - Microsoft Excel, Power BI, Tableau, R

  <mark>Marketing​</mark> - Google Analytics/Adwords, HubSpot, SalesForce



# Footer
# footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
